# Apache Configuration Template for ChimeraAI
# Generated dynamically for each project
# DO NOT edit this file directly - it will be overwritten

ServerRoot "{{APACHE_ROOT}}"
Listen {{PORT}}

# Load essential modules
LoadModule mpm_winnt_module modules/mod_mpm_winnt.so
LoadModule actions_module modules/mod_actions.so
LoadModule alias_module modules/mod_alias.so
LoadModule allowmethods_module modules/mod_allowmethods.so
LoadModule asis_module modules/mod_asis.so
LoadModule auth_basic_module modules/mod_auth_basic.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authn_file_module modules/mod_authn_file.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule authz_user_module modules/mod_authz_user.so
LoadModule autoindex_module modules/mod_autoindex.so
LoadModule cgi_module modules/mod_cgi.so
LoadModule dir_module modules/mod_dir.so
LoadModule env_module modules/mod_env.so
LoadModule include_module modules/mod_include.so
LoadModule isapi_module modules/mod_isapi.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule mime_module modules/mod_mime.so
LoadModule negotiation_module modules/mod_negotiation.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule setenvif_module modules/mod_setenvif.so

# PHP Configuration (FastCGI)
LoadModule fcgid_module modules/mod_fcgid.so

<IfModule unixd_module>
User daemon
Group daemon
</IfModule>

# ServerAdmin
ServerAdmin admin@localhost

# Server Name
ServerName {{DOMAIN}}:{{PORT}}

# Document Root
DocumentRoot "{{PROJECT_PATH}}"

<Directory "{{PROJECT_PATH}}">
    Options Indexes FollowSymLinks ExecCGI
    AllowOverride All
    Require all granted
    
    # PHP Handler
    AddHandler fcgid-script .php
    FcgidWrapper "{{PHP_CGI_PATH}}" .php
    
    # Directory Index
    DirectoryIndex index.php index.html index.htm
</Directory>

# Error Log
ErrorLog "{{LOG_PATH}}/error.log"

# Access Log
CustomLog "{{LOG_PATH}}/access.log" common

# MIME Types
TypesConfig conf/mime.types

# Default Type
DefaultType text/plain

# Host Lookup
HostnameLookups Off

# Error Documents
ErrorDocument 404 /index.php

# Include additional configs if any
IncludeOptional conf/extra/*.conf
