# Nginx Configuration Template for ChimeraAI
# Generated dynamically for each project
# DO NOT edit this file directly - it will be overwritten

# Worker Processes
worker_processes auto;

# Events Block
events {
    worker_connections 1024;
}

# HTTP Block
http {
    include       mime.types;
    default_type  application/octet-stream;

    # Logging
    access_log "{{LOG_PATH}}/access.log";
    error_log "{{LOG_PATH}}/error.log";

    # Performance
    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;
    types_hash_max_size 2048;

    # Gzip Compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss application/rss+xml font/truetype font/opentype application/vnd.ms-fontobject image/svg+xml;

    # Server Block
    server {
        listen {{PORT}};
        server_name {{DOMAIN}};

        root "{{PROJECT_PATH}}";
        index index.php index.html index.htm;

        # PHP Processing (FastCGI)
        location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }

        # Deny access to .htaccess files
        location ~ /\.ht {
            deny all;
        }

        # Deny access to hidden files
        location ~ /\. {
            deny all;
        }

        # Static Files
        location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        # Try files
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }
    }
}
